#!/bin/bash
set -e

# python3 sandbox.py
# python3 archive/problem-decompress_image_bunny.py

# python3 practice.py
# python3 note-dynamic_programming.py
python3 note-fenwick_tree.py
# python3 note-kdtree.py
# python3 note-linked_list.py
# python3 note-circular_buffer.py
# python3 note-search.py
# python3 note-segment_tree.py
# python3 note-sort.py
# python3 note-tree.py
# python3 note-trie.py
# python3 note-heap.py
# python3 note-union_find.py

# python3 problem-add_two_numbers.py
# python3 problem-amount_of_time_for_binary_tree_to_be_infected.py
# python3 problem-arithmetic_slices_ii_subsequence.py
# python3 problem-bag_of_tokens.py
# python3 problem-basic_calculator_ii.py
# python3 problem-best_time_to_by_and_sell_stock.py
# python3 problem-binary_tree_vertical_order_traversal.py
# python3 problem-buildings_with_an_ocean_view.py
# python3 problem-clone_graph.py
# python3 problem-combination_sum.py
# python3 problem-construct_binary_tree_from_preorder_and_inorder_traversal.py
# python3 problem-container_with_most_water.py
# python3 problem-convert_binary_search_to_sorted_doubly_linked_list.py
# python3 problem-count_nodes_equal_to_average_of_subtree.py
# python3 problem-count_subarrays_where_max_element_appears_at_least_k_times.py
# python3 problem-count_subarrays_with_fixed_bounds.py
# python3 problem-delete_nodes_and_return_forest.py
# python3 problem-design_circular_queue.py
# python3 problem-design_circular_deque.py
# python3 problem-diameter_of_binary_tree.py
# python3 problem-dot_product_of_two_sparse_vectors.py
# python3 problem-flood_fill.py
# python3 problem-gas_station.py
# python3 problem-house_robber.py
# python3 problem-image_overlap.py
# python3 problem-image_smoother.py
# python3 problem-insert_delete_getrandom.py
# python3 problem-integer_to_english_words.py
# python3 problem-integer_to_romain.py
# python3 problem-invert_binary_tree.py
# python3 problem-jump_game.py
# python3 problem-kth_smallest_in_bst.py
# python3 problem-letter-combinations.py
# python3 problem-longest_common_subsequence.py
# python3 problem-longest_increasing_subsequent.py
# python3 problem-lowest_common_ancestor.py
# python3 problem-lowest_common_ancestor_ii.py
# python3 problem-lru_cache.py
# python3 problem-matrix_reshape.py
# python3 problem-maximum_number_of_accepted_invitations.py
# python3 problem-maximum_number_of_operations_with_same_score_ii.py
# python3 problem-merge_accounts.py
# python3 problem-merge_intervals.py
# python3 problem-merge_sorted_array.py
# python3 problem-merge_two_sorted_lists.py
# python3 problem-minimum_area_rectangle.py
# python3 problem-minimum_remove_to_make_valid_parenthesis.py
# python3 problem-minimum_size_subarray_sum.py
# python3 problem-move_zeros.py
# python3 problem-number_of_islands.py
# python3 problem-partition_list.py
# python3 problem-pascals_triangle.py
# python3 problem-path_sum.py
# python3 problem-permutations.py
# python3 problem-powxn.py
# python3 problem-random_pick_with_weight.py
# python3 problem-remove_duplicates_from_sorted_array.py
# python3 problem-remove_duplicates_from_sorted_array_ii.py
# python3 problem-remove_element.py
# python3 problem-remove_linked_list_elements.py
# python3 problem-remove_zero_sum_consecutive_nodes_from_linked_list.py
# python3 problem-roman_to_integer.py
# python3 problem-rotate_array.py
# python3 problem-rotate_image.py
# python3 problem-rotate_list.py
# python3 problem-sequential_digits.py
# python3 problem-set_matrix_zeros.py
# python3 problem-simulate_robot.py
# python3 problem-sparse_matrix_multiplication.py
# python3 problem-spiral_matrix.py
# python3 problem-subarray_product_less_than_k.py
# python3 problem-subarray_sum_equals_k.py
# python3 problem-subsets.py
# python3 problem-sum_root_to_leaf_numbers.py
# python3 problem-task_scheduler.py
# python3 problem-the_earliest_moment_when_everyone_become_friends.py
# python3 problem-three_sum.py
# python3 problem-toeplitz_matrix.py
# python3 problem-two_sum.py
# python3 problem-unique_paths.py
# python3 problem-valid_palindrome.py
# python3 problem-valid_palindrome_ii.py
# python3 problem-valid_parenthesis.py
# python3 problem-valid_sudoku.py
# python3 problem-valid_word_abbreviation.py
# python3 problem-word_break.py
# python3 sandbox.py
